global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'Node_1'
    static_configs:
      - targets: ['89.208.197.196']

  - job_name: 'Node_2'
    static_configs:
      - targets: ['89.208.86.50']

  - job_name: 'Node_3'
    static_configs:
      - targets: ['89.208.85.234']

  - job_name: 'node'
    static_configs:
      - targets: ['nodeexporter:9100']